### ISSUE TITLE
Proposal not found when loading proposal via subgraph

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#205] opened 2023-02-14 06:20 UTC
For a split second we see an error not found page when clicking on a proposal. It then loads but would be good if we can show loading instead of not found

![Screenshot 2023-02-14 at 15 18 36](https://user-images.githubusercontent.com/39137239/218655410-69bb43c0-3156-402b-83a6-f2b5e30d90cd.jpg)

**Comment by Filipv95** [comment] 2023-02-17 14:39
@rossneilson I'am unable to reproduce this on `v3.0.0`, on `local` and `QA` envs, should this be tested somewhere else?

**Comment by rossneilson** [comment] 2023-02-18 01:27
It was found when testing subgraph on gnosis chain which so far has not been merged. So can only test from my pr right now which adds it

**Comment by Filipv95** [comment] 2023-02-20 08:49
I've menaged to replicate bug on your PR, on other env I was not able to reproduce it so I think we can close this issue if you agree?

**Closed** 2023-02-20 08:50 UTC
Labels: bug, app:Frontend, Subgraph UI Feature
