### ISSUE TITLE
Creator of discussion is not correct

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#223] opened 2023-02-22 19:06 UTC
**Description**
Created Discussion using test acc and it appeared as if I created it with my own acc. Replicable on `localhost`.

**Steps to Reproduce**
1. Spin up localhost env
2. Go to `Localhost` guild
3. Click on 'Create Discussion' button
4. Add discussion title and description
5. Click on 'Create Discussion' button to finish creating the discussion

**Expected behavior**
Creator of the discussion should be the user that is connected to the wallet.

**Screenshots**
![discussion-creator](https://user-images.githubusercontent.com/37701286/220733251-46012d44-36c0-4f6b-91de-d5680bfc0a56.jpg)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Additional context**
Could be that this behavior is only replicable on `localhost` I was not able to test it on `Gnosis` or `Ethereum` networks, if that's the case than it's not of that high PTY but should be fixed at some point since it will be needed for e.g. Automation test assertion

**Comment by rossneilson** [comment] 2023-02-27 06:50
Pretty confident this is a duplicate of #19 
Closing this and linking to older issue

**Closed by rossneilson** 2023-02-27 06:50 UTC
Labels: bug
